### ISSUE TITLE
App will hangup when quitting

### ISSUE THREAD

**Issue by RTSchriner** [launchthought/Galileo-Issues-Bugs#3]
**What happened?**
The Galileo app will sometimes go unresponsive when closing the app, the window will close but the icon will stay in the dock until force quit is called on the app.

**What did you expect to happen?**
The app to close immediately.

**How can someone else reproduce this?**

  1. Open Galileo
  2. Quit Galileo

**Comment by RTSchriner** [comment]
```
[2019-03-06 11:57:15.639] [info] child process success on port 8080
[2019-03-06 11:57:16.315] [info] INFO:galileo.model:Instantiating Galileo

[2019-03-06 11:57:16.316] [info] INFO:galileo.model:Importing keypair from file system

[2019-03-06 11:57:16.414] [info] INFO:galileo.utils:Found extant pickled object at /Users/rileyschriner/Library/Application Support/galileo/groups.bin

[2019-03-06 11:57:16.415] [info] INFO:galileo.utils:Loading pickled object from /Users/rileyschriner/Library/Application Support/galileo/groups.bin
INFO:galileo.utils:Found extant pickled object at /Users/rileyschriner/Library/Application Support/galileo/history.bin
INFO:galileo.utils:Loading pickled object from /Users/rileyschriner/Library/Application Support/galileo/history.bin

[2019-03-06 11:57:16.415] [info] INFO:galileo.utils:Found extant pickled object at /Users/rileyschriner/Library/Application Support/galileo/friends.bin
INFO:galileo.utils:Loading pickled object from /Users/rileyschriner/Library/Application Support/galileo/friends.bin
INFO:galileo.model:Registering device on network

[2019-03-06 11:57:17.310] [info] WARNING:galileo.networking:Code 0: User already registered

[2019-03-06 11:57:17.313] [info] INFO:galileo.utils:Found extant pickled object at /Users/rileyschriner/Library/Application Support/galileo/inbound_requests.bin
INFO:galileo.utils:Loading pickled object from /Users/rileyschriner/Library/Application Support/galileo/inbound_requests.bin

[2019-03-06 11:57:17.313] [info] INFO:galileo.utils:Found extant pickled object at /Users/rileyschriner/Library/Application Support/galileo/pending_requests.bin
INFO:galileo.utils:Loading pickled object from /Users/rileyschriner/Library/Application Support/galileo/pending_requests.bin
INFO:galileo.utils:Found extant pickled object at /Users/rileyschriner/Library/Application Support/galileo/accepted_requests.bin
INFO:galileo.utils:Loading pickled object from /Users/rileyschriner/Library/Application Support/galileo/accepted_requests.bin
INFO:galileo.utils:Found extant pickled object at /Users/rileyschriner/Library/Application Support/galileo/rejected_requests.bin
INFO:galileo.utils:Loading pickled object from /Users/rileyschriner/Library/Application Support/galileo/rejected_requests.bin
INFO:galileo.utils:Found extant pickled object at /Users/rileyschriner/Library/Application Support/galileo/friend_removals.bin
INFO:galileo.utils:Loading pickled object from /Users/rileyschriner/Library/Application Support/galileo/friend_removals.bin

[2019-03-06 11:57:17.313] [info] INFO:galileo.utils:Found extant pickled object at /Users/rileyschriner/Library/Application Support/galileo/group_invitations.bin
INFO:galileo.utils:Loading pickled object from /Users/rileyschriner/Library/Application Support/galileo/group_invitations.bin

[2019-03-06 11:57:17.314] [info] INFO:galileo.utils:Found extant pickled object at /Users/rileyschriner/Library/Application Support/galileo/group_requests.bin
INFO:galileo.utils:Loading pickled object from /Users/rileyschriner/Library/Application Support/galileo/group_requests.bin

[2019-03-06 11:57:17.314] [info] INFO:galileo.utils:Found extant pickled object at /Users/rileyschriner/Library/Application Support/galileo/group_removals.bin

[2019-03-06 11:57:17.315] [info] INFO:galileo.utils:Loading pickled object from /Users/rileyschriner/Library/Application Support/galileo/group_removals.bin
INFO:galileo.model:Registering device on network

[2019-03-06 11:57:18.653] [info] WARNING:galileo.networking:Code 0: User already registered
INFO:galileo.model:creating threads

[2019-03-06 11:57:18.654] [info] INFO:galileo.model:starting threads

[2019-03-06 11:57:19.466] [info]  * Environment: production
   WARNING: Do not use the development server in a production environment.

[2019-03-06 11:57:19.467] [info]    Use a production WSGI server instead.
 * Debug mode: off

[2019-03-06 11:57:19.482] [info] [19521] Failed to execute script galileod-script

[2019-03-06 11:57:19.483] [info] Traceback (most recent call last):
  File "build/galileod/galileod-script.py", line 2, in <module>
  File "click/core.py", line 764, in __call__
  File "flask/cli.py", line 557, in main
  File "click/core.py", line 717, in main
  File "click/core.py", line 1137, in invoke
  File "click/core.py", line 956, in invoke
  File "click/core.py", line 555, in invoke
  File "click/decorators.py", line 64, in new_func
  File "click/core.py", line 555, in invoke
  File "flask/cli.py", line 771, in run_command
  File "werkzeug/serving.py", line 814, in run_simple
  File "werkzeug/serving.py", line 774, in inner
  File "werkzeug/serving.py", line 660, in make_server
  File "werkzeug/serving.py", line 577, in __init__
  File "socketserver.py", line 449, in __init__
  File "http/server.py", line 137, in server_bind
  File "socketserver.py", line 463, in server_bind
OSError: [Errno 48] Address already in use

[2019-03-06 11:57:19.535] [info] execFile onClose 255 null
```

**Comment by RTSchriner** [comment]
```
[2019-03-06 11:44:27.024] [info] INFO:galileo.model:killing threads
```
